### PR TITLE
Update the code with latest KEP

### PR DESCRIPTION
**Pull request by mukhoakash**
Made the following changes:
1. Introduce the new APIs
2. Fix the code generation to use the generate-internal-groups.sh script
3. Renamed the resource name to follow package name conventions
4. Structured the generated client code
5. Updated the go version and introduced vendor directory
6. Updated README

### CODE REVIEW

**Comment by wlan0** [comment]
nicely done @mukhoakash!

**Comment by wlan0** [comment]
please fix the build errors. Otherwise, it LGTM

**Review by wlan0 — APPROVED** [review]

**Comment by mukhoakash** [comment]
> please fix the build errors. Otherwise, it LGTM

I believe this build error is due to golang version which is set here in the test-infra [file](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/container-object-storage-interface/container-object-storage-interface-api.yaml). We will have to fix those versions to handle the failures.

**Pull request merged**
