### PR TITLE
Adding a object reference that can be used as a reference to BR, BAR …

### PR DESCRIPTION
**Pull request by brahmaroutu**
…and SA

This is a discrepancy between the Spec and API definitions. BA should have following fields BucketAccessRequest and ServiceAccount of type ObjectReference instead of string.

/assign @wlan0

### CODE REVIEW

**Comment by wlan0** [comment]
I prefer this approach tbh. This is more idiomatic of how references are held in k8s api.

**Comment by wlan0** [comment]
I've added a hold because I want @xing-yang/@rrati to take a look

**Comment by rrati** [comment]
LGTM

**Pull request merged**
