### PR TITLE
monorepo: add imported controller

### PR DESCRIPTION
**Pull request by BlaineEXE**
This is the first step in merging repos, using `monorepo` as the working/feature branch.

This PR does exactly 2 things:
1. Add a new `./pkg` dir
2. `git subtree add --prefix pkg/imported-controller controller/master` where controller is https://github.com/kubernetes-sigs/container-object-storage-interface-controller

This adds all 341 controller commits (with history intact), plus the subtree commit to merge them. Due to the huge scope, no other changes are made.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
@xing-yang I see a lot of CLA issues related to the older controller repo commits. Is this something that can be worked around? I'm not sure how to resolve this otherwise, unless we squash all commits from the controller, which won't preserve history.

**Comment by xing-yang** [comment]
I see most of those commits are from Grant.  Let me ping him and see if he has a new github id.
For the ones that we couldn't figure out, maybe we can use a different id, maybe yours?

**Comment by BlaineEXE** [comment]
> For the ones that we couldn't figure out, maybe we can use a different id, maybe yours?

Is that okay to do? That will strip the original author's attribution and rewrite a few commits in the git history.

**Comment by ggriffiths** [comment]
Hi, sorry this is causing some headache.

I no longer work for Portworx or use grant@portworx.com. Because of that, I had removed grant@portworx.com from my github profile.

We can try a few things:
1. I've temporarily re-added grant@portworx.com in case the CLA check can be re-ran. I can't verify the email, so maybe that won't work.
2. I've just signed the CLA with my personal email ggp493@gmail.com if you need to re-write the commit with a new email.
3. You have my permission to squash my commits into a new commit if the above doesn't work.

**Comment by BlaineEXE** [comment]
Thanks, @ggriffiths ! It looks like that allowed the commits with your ID to pass EasyCLA. Now there is just the remaining unknown user.

If it's okay, would you leave your portworx email added on GitHub for the next 2-3 weeks while we work on merging these repos? Much appreciated!

**Comment by BlaineEXE** [comment]
I can't find the GitHub user "Niu Lechuan" associated with this commit: https://github.com/kubernetes-sigs/container-object-storage-interface-api/commit/3b88f297f8194c24bdfcb14aee644b92a62bd2cb. It seems the user may have removed their account. 

I think the best I can do in the circumstance is to rewrite the commit with my own info. It's a small doc update, so I am not concerned about validating that I believe the commit to be safe and up to my own contribution standards.

**Comment by ggriffiths** [comment]
> If it's okay, would you leave your portworx email added on GitHub for the next 2-3 weeks while we work on merging these repos? Much appreciated!

Sure, will do.

**Comment by BlaineEXE** [comment]
@xing-yang here is the response I got from TLF. We are advised to force merge without passing EasyCLA check. In this case, I think we have documented well that there is one PR not passing, and why, so we should have enough information recorded to explain if anyone asks us why.

image

**Pull request merged**
